/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laptrinhjava;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public final class InDiem extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    List<BangDiem> bangDiem = new ArrayList<>();
    public static String maMonHoc ;
   
    

    /**
     * Creates new form InDiem
     */
    public InDiem() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Bảng điểm"); 
        tableModel = (DefaultTableModel) BangDiem.getModel();
        hienThiBangDiem();
        
    }
    
    private void hienThiBangDiem() {
        
        String namHoc = chonNamHoc.getSelectedItem().toString();
        String hocKi = chonHocKi.getSelectedItem().toString();
        float tong = 0;
        float diemTB = 0 ;
        bangDiem=SinhVienDAO.layBangDiemTheoMSSV(Quanlidiem1.mssvInDiem,namHoc,hocKi);
        
        tableModel.setRowCount(0);
        
        bangDiem.forEach((ketqua) -> {
           tableModel.addRow(new Object[] {ketqua.getMaMH(), ketqua.getTenMH(),ketqua.getDiem(),ketqua.getDiemChu()
                });
       });
        
        for (BangDiem i : bangDiem) {
             if(i.getDiemChu().equals("A")){
                 tong += 4 ;
             }else if(i.getDiemChu().equals("B+")){
                 tong += 3.5 ;
             }else if(i.getDiemChu().equals("B")){
                 tong += 3 ;
             }else if(i.getDiemChu().equals("C+")){
                 tong += 2.5 ;
             }else if(i.getDiemChu().equals("C")){
                 tong += 2 ;
             }else if(i.getDiemChu().equals("D")){
                 tong += 1.5 ;
             }else if(i.getDiemChu().equals("F")){
                 tong += 0 ;
             }
        }
        
        
        diemTB = (float) (Math.round(tong/bangDiem.size()*100)/100D);
        String diemTBString  = String.valueOf(diemTB);
        if(diemTBString.equals("0.0")){
            diemTb.setText("");
        }else{
            diemTb.setText(diemTBString);
        }
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangDiem = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        chonNamHoc = new javax.swing.JComboBox<>();
        chonHocKi = new javax.swing.JComboBox<>();
        nutChon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diemTb = new javax.swing.JTextField();
        nutSuaDiem = new javax.swing.JButton();
        nutXoaDiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng điểm");

        BangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã môn", "Tên môn", "Điểm số", "Điểm chữ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BangDiem);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/logout-icon-16.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chonNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020-2021", "2021-2022", "2022-2023", "2023-2024" }));
        chonNamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonNamHocActionPerformed(evt);
            }
        });

        chonHocKi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HK1", "HK2", "HK hè" }));

        nutChon.setText("Chọn");
        nutChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutChonActionPerformed(evt);
            }
        });

        jLabel2.setText("Năm học:");

        jLabel3.setText("Học Kỳ:");

        jLabel4.setText("Điểm trung bình học kỳ:");

        diemTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemTbActionPerformed(evt);
            }
        });

        nutSuaDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        nutSuaDiem.setText("Sửa điểm");
        nutSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutSuaDiemActionPerformed(evt);
            }
        });

        nutXoaDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        nutXoaDiem.setText("Xóa điểm");
        nutXoaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutXoaDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chonNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chonHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(nutChon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nutXoaDiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                        .addComponent(nutSuaDiem)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diemTb, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jButton1)))
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(249, 249, 249))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chonNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chonHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutChon)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(diemTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(nutSuaDiem)
                    .addComponent(nutXoaDiem))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           this.setVisible(false);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chonNamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonNamHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chonNamHocActionPerformed

    private void diemTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemTbActionPerformed

    private void nutSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutSuaDiemActionPerformed
                if(maMonHoc != null){
                SuaDiem sd = new SuaDiem();
                sd.setVisible(true);
                this.setVisible(false);
                }else{
                    JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                    JOptionPane.showMessageDialog(frame,
                    "Vui lòng chọn môn học cần sửa điểm",
                    "Không thể sửa điểm",
                    JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_nutSuaDiemActionPerformed

    private void nutXoaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutXoaDiemActionPerformed
       if(maMonHoc != null){
       Component frame = null;
       int result = JOptionPane.showConfirmDialog(frame,
                        "Bạn có chắc muốn xóa điểm này của sinh viên " + Quanlidiem1.mssvInDiem,
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    SinhVienDAO.xoaDiem(Quanlidiem1.mssvInDiem, maMonHoc);
                    hienThiBangDiem();
                    maMonHoc = null ;
                }else if (result == JOptionPane.NO_OPTION){
                    hienThiBangDiem();
                    maMonHoc = null ;
                }
       }else{
                    JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                    JOptionPane.showMessageDialog(frame,
                    "Vui lòng chọn môn học cần xóa",
                    "Không thể sửa điểm",
                    JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_nutXoaDiemActionPerformed

    private void BangDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangDiemMouseClicked
        int selectedIndex =  BangDiem.getSelectedRow();
        
        if(selectedIndex >= 0){
            maMonHoc= bangDiem.get(selectedIndex).getMaMH();
        }
    }//GEN-LAST:event_BangDiemMouseClicked

    private void nutChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutChonActionPerformed
        hienThiBangDiem();
    }//GEN-LAST:event_nutChonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InDiem().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangDiem;
    private javax.swing.JComboBox<String> chonHocKi;
    private javax.swing.JComboBox<String> chonNamHoc;
    private javax.swing.JTextField diemTb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nutChon;
    private javax.swing.JButton nutSuaDiem;
    private javax.swing.JButton nutXoaDiem;
    // End of variables declaration//GEN-END:variables
}
