/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laptrinhjava;

import java.awt.Component;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QuanliSV extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    
    List<SinhVien> DSSV = new ArrayList<>();
    public static String mssvInDiem,hoTenSV,gioiTinhSV,nganhSV,khoaSV ;
    public static String searchTXT ;
    public static Date ngaySinhSV ;
    public static String index ;
    public static String tongTrang  ;
    
    /**
     * Creates new form QuanliSV
     */
    public QuanliSV() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
        hienThiDSSV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Nam = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gioiTinh = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        khoa = new javax.swing.JComboBox<>();
        nganh = new javax.swing.JComboBox<>();
        Ngay = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MSSV = new javax.swing.JTextField();
        hoTen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Thang = new javax.swing.JComboBox<>();
        nutLuu = new javax.swing.JButton();
        nutHuy = new javax.swing.JButton();
        nutXoa = new javax.swing.JButton();
        nutSuaTT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        reset = new javax.swing.JToggleButton();
        giam = new javax.swing.JButton();
        vitri = new javax.swing.JTextField();
        tongsv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tang = new javax.swing.JButton();
        timKiemTxt = new javax.swing.JTextField();
        timkiem = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel14.setText("Tháng:");

        Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007" }));

        jLabel15.setText("Năm:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Giới tính:");

        gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Ngày sinh:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Ngành:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Khóa:");

        khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K44", "K45", "K46", "K47", "K48" }));

        nganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giáo dục Tiểu học", "Giáo dục Công dân", "Giáo dục Thể chất", "Sư phạm Toán học ", "Sư phạm Tin học ", "Sư phạm Vật lý ", "Sư phạm Hóa học", "Sư phạm Sinh học", "Sư phạm Ngữ văn", "Sư phạm Lịch sử", "Sư phạm Địa lý", "Sư phạm Tiếng Anh", "Sư phạm Tiếng Pháp", "Công nghệ kỹ thuật hóa học", "Kỹ thuật vật liệu", "Quản lý công nghiệp", "Logistics và Quản lý chuỗi cung ứng", "Kỹ thuật cơ điện tử", "Kỹ thuật cơ khí", "Kỹ thuật điều khiển và tự động hóa", "Kỹ thuật điện tử - viễn thông", "Kỹ thuật điện", "Kỹ thuật cấp thoát nước", "Kỹ thuật xây dựng", "Kỹ thuật xây dựng công trình thủy", "Kỹ thuật xây dựng công trình giao", "An toàn thông tin", "Truyền thông đa phương tiện", "Khoa học máy tính", "Kỹ thuật máy tính", "Mạng máy tính và truyền thông dữ liệu", "Kỹ thuật phần mềm", "Hệ thống thông tin", "Công nghệ thông tin", "Kế toán", "Kiểm toán", "Tài chính-Ngân hàng", "Quản trị kinh doanh", "Quản trị dịch vụ du lịch và lữ hành", "Marketing", "Kinh doanh thương mại", "Kinh doanh quốc tế", "Kinh tế", "Kinh tế nông nghiệp", "Kinh tế tài nguyên thiên nhiên", "Luật", "Công nghệ thực phẩm", "Công nghệ chế biến thủy sản", "Công nghệ sau thu hoạch", "Chăn nuôi", "Thú y", "Khoa học cây trồng", "Nông học", "Bảo vệ thực vật", "Khoa học môi trường", "Quản lý tài nguyên và môi trường", "Kỹ thuật môi trường", "Quản lý đất đai", "Công nghệ rau hoa quả và cảnh quan", "Khoa học đất (chuyên ngành Quản lý đất và công nghệ phân bón)", "Nuôi trồng thủy sản", "Bệnh học thủy sản", "Quản lý thủy sản", "Thống kê", "Toán ứng dụng", "Vật lý kỹ thuật", "Hóa học", "Hóa dược", "Sinh học", "Sinh học ứng dụng", "Công nghệ sinh học", "Văn học", "Việt Nam học (chuyên ngành Hướng dẫn viên du lịch)", "Ngôn ngữ Anh", "Ngôn ngữ pháp", "Thông tin - thư viện", "Triết học", "Chính trị học", "Xă hội học", " ", " " }));

        Ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mã số sinh viên:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tên sinh viên:");

        MSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSSVActionPerformed(evt);
            }
        });

        jLabel13.setText("Ngày:");

        Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        nutLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Save-icon.png"))); // NOI18N
        nutLuu.setText("Lưu");
        nutLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutLuuActionPerformed(evt);
            }
        });

        nutHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Button-Close-icon-16.png"))); // NOI18N
        nutHuy.setText("Hủy");
        nutHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutHuyActionPerformed(evt);
            }
        });

        nutXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        nutXoa.setText("Xóa");
        nutXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutXoaActionPerformed(evt);
            }
        });

        nutSuaTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        nutSuaTT.setText("Sửa thông tin");
        nutSuaTT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nutSuaTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutSuaTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(nutSuaTT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nutXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nutLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nutHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nutLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutSuaTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/10207-man-student-light-skin-tone-icon-64.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Họ tên", "Giới tính", "Ngày sinh", "Ngành", "Khóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(26);
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        giam.setText("<");
        giam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giamActionPerformed(evt);
            }
        });

        vitri.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tongsv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tongsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongsvActionPerformed(evt);
            }
        });

        jLabel4.setText("/");

        tang.setText(">");
        tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangActionPerformed(evt);
            }
        });

        timKiemTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemTxtActionPerformed(evt);
            }
        });

        timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/search-icon-16.png"))); // NOI18N
        timkiem.setText("Tìm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timKiemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(giam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tongsv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timkiem)
                            .addComponent(timKiemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(tang)
                            .addComponent(tongsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giam))
                        .addGap(17, 17, 17)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void hienThiDSSV() {
        if(index == null){
            index = "1";
        }
        if(searchTXT == null){
            DSSV = SinhVienDAO.lay5SV(index);
            tinhTrang();
            tongsv.setText(tongTrang);
        }else{
            timKiemTxt.setText(searchTXT);
            DSSV = SinhVienDAO.timKiemSV(searchTXT, searchTXT,index);
            tinhTrangTimKiem();
            tongsv.setText(tongTrang);
        }
        
        
        tableModel.setRowCount(0);
        
        DSSV.forEach((student) -> {
           tableModel.addRow(new Object[] {student.getMSSV(), 
                student.getHoTen(), student.getGioiTinh(), student.getNgaySinh(),student.getNganh(),student.getKhoa()});
       });
       
        if(tongTrang.equals("0")){
            vitri.setText("0");
        }else{
            vitri.setText(index);
        }
   }
    private void tinhTrang(){
        if(Integer.parseInt(SinhVienDAO.layTongSoSV())%5 == 0){
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSV())/5);
        }else{
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSV())/5 +1);
        }
    }
    private void tinhTrangTimKiem(){
        if(Integer.parseInt(SinhVienDAO.layTongSoSVTimKiem(searchTXT))%5 == 0){
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSVTimKiem(searchTXT))/5);
        }else{
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSVTimKiem(searchTXT))/5 +1);
        }
    }
    private void NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NgayActionPerformed

    private void MSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MSSVActionPerformed

    private void nutLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutLuuActionPerformed
        String mssv = MSSV.getText();
        String hoten = hoTen.getText();
        String gioitinh= gioiTinh.getSelectedItem().toString();
        String ngay = Ngay.getSelectedItem().toString();
        String thang = Thang.getSelectedItem().toString();
        String nam = Nam.getSelectedItem().toString();
        String ngaysinh = nam+thang+ngay ;
        String nganhhoc = nganh.getSelectedItem().toString();
        String khoahoc = khoa.getSelectedItem().toString();
        if(mssv.equals("") || hoten.equals("")) {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng nhập đầy đủ",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);

        }else if(mssv.charAt(0) != 'B' || mssv.length() != 8){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Sai định dạng mã số sinh viên phải bắt đầu từ B và có 8 ký tự",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }else if(SinhVienDAO.laySV(mssv) != null){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Sinh viên đã tồn tại",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }else{
            SinhVienDAO.themSV(mssv, hoten, gioitinh, ngaysinh, nganhhoc, khoahoc);
            hienThiDSSV();
            MSSV.setText("");
            hoTen.setText("");
        }

    }//GEN-LAST:event_nutLuuActionPerformed

    private void nutHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutHuyActionPerformed
        MSSV.setText("");
        hoTen.setText("");
    }//GEN-LAST:event_nutHuyActionPerformed

    private void nutXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutXoaActionPerformed
        if(mssvInDiem != null){
            Component frame = null;
            List<KetQua> list = SinhVienDAO.layKQCuaSV(mssvInDiem);
            int result = JOptionPane.showConfirmDialog(frame,
                "Bạn có chắc muốn xóa sinh viên này",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                if( !list.isEmpty() ){
                    JOptionPane.showMessageDialog(frame,
                        "Không thể xóa vì sinh viên đang có điểm",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                    hienThiDSSV();
                }else{
                    SinhVienDAO.xoaSV(mssvInDiem);
                    hienThiDSSV();
                }
                mssvInDiem = null;
            }else if (result == JOptionPane.NO_OPTION){
                hienThiDSSV();
                mssvInDiem = null;
            }
        }else{
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng chọn sinh viên cần xóa",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nutXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedIndex =  jTable1.getSelectedRow();

        if(selectedIndex >= 0){
            mssvInDiem = DSSV.get(selectedIndex).getMSSV();
            hoTenSV = DSSV.get(selectedIndex).getHoTen();
            gioiTinhSV = DSSV.get(selectedIndex).getGioiTinh();
            ngaySinhSV = DSSV.get(selectedIndex).getNgaySinh();
            nganhSV = DSSV.get(selectedIndex).getNganh();
            khoaSV = DSSV.get(selectedIndex).getKhoa();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void tangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangActionPerformed
        int i =Integer.parseInt(index);
        i++;
        if(i<=Integer.parseInt(tongTrang)){
            index = String.valueOf(i);
            hienThiDSSV();
        }
    }//GEN-LAST:event_tangActionPerformed

    private void tongsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tongsvActionPerformed

    private void giamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giamActionPerformed

        int i =Integer.parseInt(index);
        i--;
        if(i>0){
            index = String.valueOf(i);
            hienThiDSSV();
        }
    }//GEN-LAST:event_giamActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        timKiemTxt.setText("");
        searchTXT = null;
        index = "1";
        hienThiDSSV();
    }//GEN-LAST:event_resetActionPerformed

    private void nutSuaTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutSuaTTActionPerformed
        if(mssvInDiem!=null){
            SuaThongTinSV suaTTSV = new SuaThongTinSV();
            suaTTSV.setVisible(true);
            this.setVisible(false);
        }else{
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng chọn sinh viên cần sửa thông tin",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nutSuaTTActionPerformed

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed

        searchTXT = timKiemTxt.getText();
        if(searchTXT.equals("")){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng nhập vào ô tìm kiếm",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }else{
            index="1";
            hienThiDSSV();
        }
    }//GEN-LAST:event_timkiemActionPerformed

    private void timKiemTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MSSV;
    private javax.swing.JComboBox<String> Nam;
    private javax.swing.JComboBox<String> Ngay;
    private javax.swing.JComboBox<String> Thang;
    private javax.swing.JButton giam;
    private javax.swing.JComboBox<String> gioiTinh;
    private javax.swing.JTextField hoTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> khoa;
    private javax.swing.JComboBox<String> nganh;
    private javax.swing.JButton nutHuy;
    private javax.swing.JButton nutLuu;
    private javax.swing.JButton nutSuaTT;
    private javax.swing.JButton nutXoa;
    private javax.swing.JToggleButton reset;
    private javax.swing.JButton tang;
    private javax.swing.JTextField timKiemTxt;
    private javax.swing.JToggleButton timkiem;
    private javax.swing.JTextField tongsv;
    private javax.swing.JTextField vitri;
    // End of variables declaration//GEN-END:variables
}
