/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laptrinhjava;


import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Quanlidiem1 extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    
    List<SinhVien> DSSV = new ArrayList<>();
    public static String mssvInDiem,hoTenSV,gioiTinhSV,nganhSV,khoaSV ;
    public static String searchTXT ;
    public static Date ngaySinhSV ;
    public static String index ;
    public static String tongTrang  ;
    /**
     * Creates new form Quanlidiem1
     */
    public Quanlidiem1() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
        hienThiMaMH();
        hienThiDSSV();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diem = new javax.swing.JTextField();
        namhoc = new javax.swing.JComboBox<>();
        hocki = new javax.swing.JComboBox<>();
        nutLuuDiem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mamh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        timKiemTxt = new javax.swing.JTextField();
        timkiem1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nutInBangDiem = new javax.swing.JButton();
        reset1 = new javax.swing.JToggleButton();
        giam1 = new javax.swing.JButton();
        vitri = new javax.swing.JTextField();
        tongsv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tang1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Học kỳ:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Năm học:");

        diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemActionPerformed(evt);
            }
        });

        namhoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020-2021", "2021-2022", "2022-2023", "2023-2024" }));

        hocki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HK1", "HK2", "HK Hè" }));

        nutLuuDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Save-icon.png"))); // NOI18N
        nutLuuDiem.setText("Lưu");
        nutLuuDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutLuuDiemActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Button-Close-icon-16.png"))); // NOI18N
        jButton3.setText("Hủy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/gpa-icon-64.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐIỂM");

        mamh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mamhActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mã môn học:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Điểm:");

        timkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/search-icon-16.png"))); // NOI18N
        timkiem1.setText("Tìm");
        timkiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiem1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Họ tên", "Giới tính", "Ngày sinh", "Ngành", "Khóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(26);
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        nutInBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/open-file-icon-16.png"))); // NOI18N
        nutInBangDiem.setText("Xem bảng điểm ");
        nutInBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutInBangDiemActionPerformed(evt);
            }
        });

        reset1.setText("Reset");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });

        giam1.setText("<");
        giam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giam1ActionPerformed(evt);
            }
        });

        vitri.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tongsv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tongsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongsvActionPerformed(evt);
            }
        });

        jLabel8.setText("/");

        tang1.setText(">");
        tang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nutInBangDiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(giam1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tongsv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tang1)
                        .addGap(5, 5, 5)
                        .addComponent(reset1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(diem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(hocki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mamh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nutLuuDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(namhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timKiemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mamh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(nutLuuDiem))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timKiemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiem1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nutInBangDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giam1)
                    .addComponent(vitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tongsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tang1)
                    .addComponent(reset1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tang1ActionPerformed
        int i =Integer.parseInt(index);
        i++;
        if(i<=Integer.parseInt(tongTrang)){
            index = String.valueOf(i);
            hienThiDSSV();
        }
    }//GEN-LAST:event_tang1ActionPerformed

    private void tongsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tongsvActionPerformed

    private void giam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giam1ActionPerformed

        int i =Integer.parseInt(index);
        i--;
        if(i>0){
            index = String.valueOf(i);
            hienThiDSSV();
        }
    }//GEN-LAST:event_giam1ActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        timKiemTxt.setText("");
        searchTXT = null;
        index = "1";
        mssvInDiem = null;
        hienThiDSSV();
    }//GEN-LAST:event_reset1ActionPerformed

    private void nutInBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutInBangDiemActionPerformed
        if(mssvInDiem != null){
            InDiem id = new InDiem();
            id.setVisible(true);
            id.setLocationRelativeTo(null);
        }else{
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng chọn sinh viên cần xem điểm",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nutInBangDiemActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedIndex =  jTable1.getSelectedRow();

        if(selectedIndex >= 0){
            mssvInDiem = DSSV.get(selectedIndex).getMSSV();
            hoTenSV = DSSV.get(selectedIndex).getHoTen();
            gioiTinhSV = DSSV.get(selectedIndex).getGioiTinh();
            ngaySinhSV = DSSV.get(selectedIndex).getNgaySinh();
            nganhSV = DSSV.get(selectedIndex).getNganh();
            khoaSV = DSSV.get(selectedIndex).getKhoa();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void timkiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiem1ActionPerformed

        searchTXT = timKiemTxt.getText();
        if(searchTXT.equals("")){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng nhập vào ô tìm kiếm",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }else{
            index="1";
            hienThiDSSV();
        }
    }//GEN-LAST:event_timkiem1ActionPerformed

    private void mamhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mamhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mamhActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        diem.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nutLuuDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutLuuDiemActionPerformed
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        String maMH = mamh.getSelectedItem().toString();
        String namHoc = namhoc.getSelectedItem().toString();
        String hocKi = hocki.getSelectedItem().toString();
        String diemChu = null;

        if(mssvInDiem != null){
            KetQua kq =SinhVienDAO.kiemTraKetQua(maMH, mssvInDiem, namHoc, hocKi) ;
            try {
                float Diem = Float.parseFloat(diem.getText());
                if(Diem<0 || Diem>10){
                    JOptionPane.showMessageDialog(frame,
                        "Điểm phải nằm trong khoảng từ 0 đến 10",
                        "Không thể nhập điểm",
                        JOptionPane.ERROR_MESSAGE);
                }else if(kq!=null){
                    JOptionPane.showMessageDialog(frame,
                        "Đã tồn tại",
                        "Không thể nhập điểm",
                        JOptionPane.ERROR_MESSAGE);
                }else{
                    if(Diem>=9 && Diem<=10){
                        diemChu = "A";
                    }else if(Diem>=8 && Diem<9){
                        diemChu = "B+";
                    }else if(Diem>=7 && Diem<8){
                        diemChu = "B";
                    }else if(Diem>=6.5 && Diem<7){
                        diemChu = "C+";
                    }else if(Diem>=5.5 && Diem<6.5){
                        diemChu = "C";
                    }else if(Diem>=4 && Diem<5.5){
                        diemChu = "D";
                    }else {
                        diemChu= "F" ;
                    }
                    String DiemS = String.valueOf(Diem);
                    SinhVienDAO.nhapKetQua(maMH, mssvInDiem, DiemS, namHoc, hocKi,diemChu);
                    JOptionPane.showMessageDialog(frame,
                        "Thành công",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(frame,
                    "Sai định dạng",
                    "Không thể nhập điểm",
                    JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(frame,
                "Vui lòng chọn sinh viên để nhập điểm",
                "Không thể nhập điểm",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nutLuuDiemActionPerformed

    private void diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemActionPerformed
    private void hienThiDSSV() {
        if(index == null){
            index = "1";
        }
        if(searchTXT == null){
            DSSV = SinhVienDAO.lay5SV(index);
            tinhTrang();
            tongsv.setText(tongTrang);
        }else{
            timKiemTxt.setText(searchTXT);
            DSSV = SinhVienDAO.timKiemSV(searchTXT, searchTXT,index);
            tinhTrangTimKiem();
            tongsv.setText(tongTrang);
        }
        
        
        tableModel.setRowCount(0);
        
        DSSV.forEach((student) -> {
           tableModel.addRow(new Object[] {student.getMSSV(), 
                student.getHoTen(), student.getGioiTinh(), student.getNgaySinh(),student.getNganh(),student.getKhoa()});
       });
       
        if(tongTrang.equals("0")){
            vitri.setText("0");
        }else{
            vitri.setText(index);
        }
   }
       
    private void hienThiMaMH(){
        List<MonHoc> list  = SinhVienDAO.layMonHoc();
        for (MonHoc i : list) {
            mamh.addItem(i.getMaMH());
        }
    }
    private void tinhTrang(){
        if(Integer.parseInt(SinhVienDAO.layTongSoSV())%5 == 0){
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSV())/5);
        }else{
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSV())/5 +1);
        }
    }
    private void tinhTrangTimKiem(){
        if(Integer.parseInt(SinhVienDAO.layTongSoSVTimKiem(searchTXT))%5 == 0){
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSVTimKiem(searchTXT))/5);
        }else{
            tongTrang = String.valueOf(Integer.parseInt(SinhVienDAO.layTongSoSVTimKiem(searchTXT))/5 +1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diem;
    private javax.swing.JButton giam1;
    private javax.swing.JComboBox<String> hocki;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> mamh;
    private javax.swing.JComboBox<String> namhoc;
    private javax.swing.JButton nutInBangDiem;
    private javax.swing.JButton nutLuuDiem;
    private javax.swing.JToggleButton reset1;
    private javax.swing.JButton tang1;
    private javax.swing.JTextField timKiemTxt;
    private javax.swing.JToggleButton timkiem1;
    private javax.swing.JTextField tongsv;
    private javax.swing.JTextField vitri;
    // End of variables declaration//GEN-END:variables
}
