/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laptrinhjava;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class SuaDiem extends javax.swing.JFrame {

    /**
     * Creates new form SuaDiem
     */
    public SuaDiem() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nutCapNhatDiem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        diemSua = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập điểm:");

        nutCapNhatDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        nutCapNhatDiem.setText("Cập nhật");
        nutCapNhatDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutCapNhatDiemActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/logout-icon-16.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nutCapNhatDiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(diemSua, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(diemSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nutCapNhatDiem)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutCapNhatDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutCapNhatDiemActionPerformed
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        try {
            float Diem = Float.parseFloat(diemSua.getText());
            String diemchumoi = null;
            if(Diem<0 || Diem>10){
              JOptionPane.showMessageDialog(frame,
                "Điểm phải nằm trong khoảng từ 0 đến 10",
                "Không thể nhập điểm",
                JOptionPane.ERROR_MESSAGE);
            }else{
            if(Diem>=9 && Diem<=10){
                diemchumoi = "A";
            }else if(Diem>=8 && Diem<9){
                diemchumoi = "B+";
            }else if(Diem>=7 && Diem<8){
                diemchumoi = "B";
            }else if(Diem>=6.5 && Diem<7){
                diemchumoi = "C+";
            }else if(Diem>=5.5 && Diem<6.5){
                diemchumoi = "C";
            }else if(Diem>=4 && Diem<5.5){
                diemchumoi = "D";
            }else {
                diemchumoi= "F" ;
            }
            String diemmoi = String.valueOf(Diem);
            SinhVienDAO.suaDiem(Quanlidiem1.mssvInDiem, InDiem.maMonHoc, diemmoi, diemchumoi);
            this.setVisible(false);
            InDiem indiem = new InDiem();
            indiem.setVisible(true);
            InDiem.maMonHoc= null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame,
                "Sai cú pháp",
                "Không thể nhập điểm",
                JOptionPane.ERROR_MESSAGE);
        }
        
        
        
      
        
        
       
        
    }//GEN-LAST:event_nutCapNhatDiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        InDiem indiem = new InDiem();
        indiem.setVisible(true);
        InDiem.maMonHoc =null;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SuaDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SuaDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SuaDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SuaDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SuaDiem().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diemSua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nutCapNhatDiem;
    // End of variables declaration//GEN-END:variables
}
